### ISSUE TITLE
Prev Issue #6 is not dupe

### ISSUE THREAD

**Issue by Lisk39** [DolphinLHT/Simple-Chat#10]
Our group found a bug that was marked as dupe (issue #6 written by Benjamin-Pasternak) we go into more detail on why it was not a duplicate issue in the comments in the closed issue. We created this because it didn't seem anyone would see the details on the original issue otherwise.

**Comment by DolphinLHT** [comment]
Hi. That's fine because I'm not the one who give you points and I didn't even delete it. TA can still see it and give you your points so don't be worried about that and just include it in your report.

**Comment by symxmyz233** [comment]
Yes, I can see all. Check comments in these issues.
