### ISSUE TITLE
[Duplicated issue with issue#2]Password data may be potentially transmitted in plaintext

### ISSUE THREAD

**Issue by sagjig** [DolphinLHT/Simple-Chat#3]
Hello, I may have found an issue regarding password integrity and leakage in your code/methodology:

Before the password is written to `user_password.db,` it seems to not be encrypted properly even as the storage code expects an encrypted string. @jayko8899 I believe has also detailed the same potential issue - we may not be getting our passwords fully encrypted or encrypted without malformity before they are stored.
Thank you.

**Comment by DolphinLHT** [comment]
Closing because of duplicated contents of issues

**Comment by symxmyz233** [comment]
Hi sagjig, **it is a bug, but someone has found it earlier than you**, so I am sorry you can not get points from this issue.
