### ISSUE TITLE
[Duplicated issue with issue#2]The database is not secured 

### ISSUE THREAD

**Issue by Benjamin-Pasternak** [DolphinLHT/Simple-Chat#6]
We can just open the database and see all info (unhashed username and passwords) by downloading sqlite browser (a database browser).

**Comment by DolphinLHT** [comment]
Closing because of duplicated content of issue

**Comment by Lisk39** [comment]
This is not a duplicate with #2 as it doesn't deal with how information is put into the database, but rather that the database itself is compromised. We are not concerned with individual usernames and passwords or their integrity but the fact that a person can just view all the info within the database at will. The database is not password protected or secured in any way.

**Comment by Lisk39** [comment]
![Screen_Shot_2021-12-03_at_9 53 49_PM](https://user-images.githubusercontent.com/19292135/144695548-53ed5de9-ace7-47fd-8e6b-fe9f96b89d09.png)

**Comment by Lisk39** [comment]
we created an account with username and password the, the and you can see both in plaintext

**Comment by symxmyz233** [comment]
It told the same thing as issues 2 in the first part, but you go further, **so it is a normal bug now in total. But based on your part of finding, it can only be count as a minor one.**
But still, you did a good jib.
