### ISSUE TITLE
Issue found

### ISSUE THREAD

**Issue by applepassion4** [DolphinLHT/Simple-Chat#8]
Running the client before the server cause then registering is causing the client to through errors

**Comment by applepassion4** [comment]
screenshot of the error 
![image](https://user-images.githubusercontent.com/53684246/144704265-95c71947-fd56-4101-90c9-d6b2fba5ca52.png)

**Comment by DolphinLHT** [comment]
READ.ME:"Simulate the server first."

**Comment by symxmyz233** [comment]
**It is not a bug.**
